name: "Update deployment status"
description: "Update status of an external deployment to Prodvana."
inputs:
  deployment_id:
    description: "The deployment ID returned from record-deployment action"
    required: true
  failed:
    description: "Mark deployment as failing."
    type: boolean
    defualt: false
  auth_context:
    description: "pvnctl auth context to use. If you're using this Action with init-pvnctl, leave as the default"
    required: true
    default: "default"
outputs: {}
runs:
  using: "composite"
  steps:
    - name: pvnctl deployments update-status
      shell: bash
      run: |
        set -euxo pipefail
        pvnctl auth context use ${{ inputs.auth_context }}
        CMD="pvnctl releases update-status ${{ inputs.deployment_id }}"
        if [[ "${{ inputs.failed }}" == "true" ]]; then
          CMD="$CMD --status=failed"
        else
          CMD="$CMD --status=succeeded"
        fi
        eval "${CMD}"
